name: Deploy backend to production

# Manual deployment trigger
on:
  workflow_dispatch:
    inputs:
      BUMP_VERSION:
        type: choice
        description: "Bump version, eg. 'major', 'minor', or 'patch'"
        required: true
        options:
          - 'major'
          - 'minor'
          - 'patch'
        default: 'patch'


env:
  BUILD_ARTIFACT_NAME: 'gosqas-be'                    # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_NAME: 'gdtprodbackend'             # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'packages/backend'    # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
            
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: ${{ github.event.inputs.BUMP_VERSION }}

    - name: 'Build node.js project'
      shell: bash
      env:
        APP_VERSION: ${{ steps.bump_version.outputs.new_tag }}
      run: |
        echo $APP_VERSION
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        popd
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ${{ env.BUILD_ARTIFACT_NAME }}-${{ steps.bump_version.outputs.new_tag }}
        path: packages/backend/dist/**
   
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      id: download
      with:
        name: ${{ env.BUILD_ARTIFACT_NAME }}-${{ needs.build.outputs.new_tag }}
    - name: Deploy to production
      run: |
        curl -X POST \
            --data-binary ${{ env.BUILD_ARTIFACT_NAME }}-${{ needs.build.outputs.new_tag }} \
            -H "Authorization: Bearer ${{ secrets.AZURE_ACCESS_TOKEN }}" \
            "https://${{ env.AZURE_FUNCTIONAPP_NAME }}.scm.azurewebsites.net/api/zipdeploy"
