name: On Push Frontend

on:
  push:
    branches:
      - main
    paths:
      - packages/frontend/**
      - .github/workflows/fe_on_push.yml
  pull_request:
    branches:
      - main

jobs:
  backend-run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0

    - uses: ./.github/actions/setup-backend

    # Note: warnings like the below are ok for now; the library doing the complaining is mocked in the tests.
    # WARNING: Failed to detect the Azure Functions runtime. Switching "@azure/functions" package to test mode - not all features are supported.
    - name: Run Backend Unit Tests
      working-directory: packages/backend
      run: ./scripts/run_unit_tests.sh

  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: build frontend
        working-directory: packages/frontend
        run: |
          npm ci
          npx nuxi build --preset=azure
          npm run coverage
        env:
          FRONTEND_URL: https://red-stone-00f5d251e.5.azurestaticapps.net/
      - name: deploy frontend
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./packages/frontend
        run: |
          npx @azure/static-web-apps-cli deploy .output/public/ --api-location .output/server/ --env production --deployment-token  ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: packages
          path: packages/frontend/.output/**

