name: "Selenium UI Testing"
description: "Setup Selenium for UI Automated Testing"

on:
  push:
    branches: 
      -main
  pull_request:
    branches:
      -main

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.x'
      
      - name: Install Firefox
        run: |
          sudo install -d -m 0755 /etc/apt/keyrings
          wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
          cat <<EOF | sudo tee /etc/apt/sources.list.d/mozilla.sources
          Types: deb
          URIs: https://packages.mozilla.org/apt
          Suites: mozilla
          Components: main
          Signed-By: /etc/apt/keyrings/packages.mozilla.org.asc
          EOF
          echo '
          Package: *
          Pin : origin packages.mozilla.org
          Pin-Priority: 1000
          ' | sudo tee /etc/apt/preferences.d/mozilla
          sudo apt-get update && sudo apt-get install firefox
          echo "Firefox installed successfuly!"

      - name: Install Firefox Webdriver
        run: | 
          echo "Installing Firefox Webdriver!"
          wget "https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz"
          sudo tar -xvf geckodriver-v0.36.0-linux64.tar.gz
          sudo mv geckodriver /usr/bin/geckodriver
          sudo chown root:root /usr/bin/geckodriver
          sudo chmod +x /usr/bin/geckodriver
          echo "Firefox Webdriver installed successfully!"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install Selenium
        run: |
          python -m pip install selenium

      - name: Run Test Script
        run: |
          python ./.github/workflows/selenium_test_python.py

